### ISSUE TITLE
New routing based on GitHub routes

### ISSUE THREAD

**Issue by resamsel** [resamsel/translatr#87]
Routes should behave like this: /:username/:projectname/locale/:localename

The project name must be unique per user and needs to match the name pattern. No migration is necessary, as names not matching the pattern are still valid path names and should be encoded (slashes need to be escaped such that paths are still valid). Project names that match the exclude list need to be migrated, though. Those should get a random suffix.

The locale name must be unique per project and needs to be URL encoded (like project names).

# Patterns

**Name pattern**: a-zA-Z0-9_.-

**Username exclude list**: project(s), user(s), profile, activity, login, logout, authenticate, accounts, locale, key, command, api, javascriptRoutes, assets.

**Project name exclude list**: projects, activity, linkedAccount(s), accessTokens, settings.

# TODO
- [x] /:username
- [x] /:username/:projectname
- [x] /:username/:projectname/locales
- [x] /:username/:projectname/keys
- [x] /:username/:projectname/locale/:localename
- [x] /:username/:projectname/key/:keyname
- [x] /:username/:projectname/members
- [x] /:username/:projectname/activity
- [x] User: Changing username must adhere to the username exclude list
- [x] User: Migration: existing usernames matching the username exclude list must be renamed
- [x] User: Add integration test for routes
- [x] Project: Names must be URL encoded to avoid slashes in the path
- [x] Project: When changing the owner of a project, the project might conflict with a project of the target user -> the project needs to be renamed first
- [x] Project: Changing project name must adhere to the project name exclude list
- [x] Project: ID must be visible somewhere to be able to copy it into .translatr.yml
- [x] Project: Migration: existing project names matching the project name exclude list must be renamed
- [x] Project: Add integration test for routes
- [x] Locale: Names must be URL encoded to avoid slashes in the path
- [x] Key: Names must be URL encoded to avoid slashes in the path
